// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcqHWRmyB2xEdwWQV0CK6ly_7Imb3i4WM',
    appId: '1:529146430088:web:81fe2563f3e4e578b5953d',
    messagingSenderId: '529146430088',
    projectId: 'thedarji-222b2',
    authDomain: 'thedarji-222b2.firebaseapp.com',
    storageBucket: 'thedarji-222b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxo87GaDrB8Vj2ZVuuHUDE4KyBk8BXBY0',
    appId: '1:529146430088:android:a42fb6b942b8a0acb5953d',
    messagingSenderId: '529146430088',
    projectId: 'thedarji-222b2',
    storageBucket: 'thedarji-222b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlif9M7CILT-UWjNzLxQHlrWHMtkFzDRs',
    appId: '1:529146430088:ios:92d015d03417db55b5953d',
    messagingSenderId: '529146430088',
    projectId: 'thedarji-222b2',
    storageBucket: 'thedarji-222b2.appspot.com',
    iosClientId: '529146430088-drqsveut7s7g7fc2nvqr8m47l7kob4kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.darji',
  );
}
